// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table entities.user {
  user_id bigint [increment, primary key]
  username varchar(255) [not null, unique] //we don't do this pk, so the user is able to change it
  email varchar(255) [not null, unique]
  password varchar(512) [not null] //this would be a hashed string (bcrypt/Argon2)
  role varchar(50) [not null]
  registration_date timestamp [not null, default: `CURRENT_TIMESTAMP`]
  checks {
    `role in ('ADMIN', 'VERIFIED_USER', 'NOT_VERIFIED_USER')` [name: 'chk_user_role']
  }
  indexes {
    (username) [name: 'idx_user_username']
    (email) [name: 'idx_user_email']
    (role) [name: 'idx_user_role']
  }
}

Table entities.person {
  person_id bigint [increment, primary key]
  first_name varchar(255)
  middle_name varchar(255)
  last_name varchar(255)
  birth_date date
  sex varchar [note: 'M/F/N']
  tax_id varchar(255) [unique]
  user_id bigint [unique, not null, ref: - entities.user.user_id]
  registration_date timestamp [default: `CURRENT_TIMESTAMP`]
  checks {
    `sex IN ('M','F','N')` [name: 'chk_gender_values']
  }
  indexes {
    user_id
    tax_id
  }
}

Table entities.company {
  company_id bigint [increment, primary key]
  company_name varchar(255)
  contact_person_id bigint [not null, ref: - entities.person.person_id]
  tax_id varchar(255) [unique, not null]
  user_id bigint [unique, not null, ref: - entities.user.user_id]
  registration_date timestamp [default: `CURRENT_TIMESTAMP`]
  indexes {
    user_id
    tax_id
  }
}

Table entities.client {
  client_id bigint [increment, primary key]
  entity_type varchar(255) [note: "'LEGAL_ENTITY','PERSON'"]
  person_id bigint [ref: - entities.person.person_id]
  company_id bigint [ref: - entities.company.company_id]
  registration_date timestamp [default: `CURRENT_TIMESTAMP`]
  checks {
    `(person_id IS NOT NULL AND company_id IS NULL) OR (company_id IS NOT NULL AND person_id IS NULL)` [name: 'chk_entity_exists_client']
  }
  indexes {
    entity_type
    company_id
    person_id
  }
}

Table vehicles.vehicle_catalog {
  catalog_id integer [increment, primary key]
  vehicle_type varchar(255) [note: "'CAR','MOTORCYCLE'"]
  brand_name varchar(255)
  model_name varchar(255)
  model_year integer
  indexes {
    brand_name
    model_name
    (vehicle_type,brand_name)
  }
}

Table vehicles.user_vehicles {
  vehicle_id bigint [increment, primary key]
  client_id bigint [not null, ref: > entities.client.client_id]
  catalog_id integer [not null, ref: - vehicles.vehicle_catalog.catalog_id]
  license_plate varchar(255) [not null]
  color varchar(255) [not null]
  notes varchar(4000)
  registration_date timestamp [default: `CURRENT_TIMESTAMP`]
  indexes {
    (client_id,catalog_id,license_plate) [unique]
    client_id
  }
}

Table entities.profession {
  profession_id integer [increment, primary key]
  profession_name varchar(255)
  description varchar(255)
}

Table entities.skill   {
  skill_id integer [increment, primary key]
  skill_name varchar(255)
}

Table entities.service_provider {
  provider_id bigint [increment, primary key]
  person_id bigint [ref: - entities.person.person_id]
  company_id bigint [ref: - entities.company.company_id]
  profession_id integer [not null, ref: > entities.profession.profession_id]
  service_base_location geometry
  service_radius_meters integer
  indexes {
    profession_id
  }
  checks {
    `(person_id IS NOT NULL AND company_id IS NULL) OR (company_id IS NOT NULL AND person_id IS NULL)` [name: 'chk_entity_exists_provider']
  }
}

Table entities.provider_skill {
  provider_id bigint [ref: > entities.service_provider.provider_id]
  skill_id integer [ref: > entities.skill.skill_id]
  indexes {
    (provider_id, skill_id) [pk] // composite primary key
    }
}

//Composite foreign key
// Ref: entities.service_provider.(provider_id,skill_id) - entities.spesialist_skill.(spesialist_id,skill_id)

Table requests.request_status_def {
  request_status_id bigint [primary key]
  request_status_name varchar(255) [not null, note: 'Pending, Accepted, Completed, Cancelled, Expired']
  // possible extra statuses: quoted/quoteAcceptedByClient/providerOnTheirWay/Completed/Cancelled
}

Table requests.service_requests {
  request_id bigint [increment, primary key]
  client_id bigint [not null, ref: > entities.client.client_id]
  vehicle_id bigint [not null, ref: > vehicles.user_vehicles.vehicle_id]
  // This enforces 1 mechanic per request. It is nullable because
  // when a client first sends a request, no mechanic has accepted it yet.
  provider_id bigint [ref: > entities.service_provider.provider_id]
  request_status_id bigint [not null, ref: - requests.request_status_def.request_status_id]
  requested_at timestamp
  provider_accepted_at timestamp
  completed_at timestamp
  incident_location geometry
  // payment_id integer [ref: - payment.payment_id]
  indexes {
    client_id
    provider_id
    request_status_id
    // payment_id
  }
}

Table requests.review_scale_def {
  review_scale_id integer [primary key]
  description varchar(255)
}

Table requests.review {
  review_id bigint [increment, primary key]
  request_id bigint [not null, ref: - requests.service_requests.request_id]
  review_scale_id integer [not null, ref: - requests.review_scale_def.review_scale_id]
  indexes {
    request_id
    review_scale_id
    }
  }

  // All media (photos, videos, PDFs) for a request go here
Table requests.request_attachments {
  attachment_id bigint [increment, primary key]
  request_id bigint [not null, ref: > requests.service_requests.request_id, note: 'Allows multiple attachments per request']
  file_url varchar(255) [not null, note: 'S3/Cloud storage path']
  attachment_type varchar(255) [not null, note: 'image, video, or document']
  uploaded_at timestamp [default: `CURRENT_TIMESTAMP`]

  indexes {
    request_id
  }
}

// All OBD fault codes submitted for a request go here
Table requests.request_obd_codes {
  id bigint [increment, primary key]
  request_id bigint [not null, ref: > requests.service_requests.request_id, note: 'Allows multiple OBD codes per request']
  obd_code varchar(255) [not null, note: 'e.g., P0420, P0301']

  indexes {
    request_id
  }
}

Table requests.vehicle_symptom_def {
  // CHECK_ENGINE_LIGHT; STRANGE_NOISE; BATTERY_ISSUE
  // FLAT_TIRE; NO_START; OVERHEATING; BRAKE_PROBLEM
  // OIL_LEAK; EXCESSIVE_SMOKE; OTHER
  symptom_code varchar(255) [primary key]
  symptom_desc varchar(255)
}

Table requests.request_vehicle_symptom {
  symptom_code varchar(255) [ref: - requests.vehicle_symptom_def.symptom_code]
  request_id bigint [not null, ref: > requests.service_requests.request_id]
  custom_symptom_description varchar(255) [note: 'Used when symptom_code is OTHER, or for extra request-specific details']
indexes {
      (symptom_code, request_id) [pk] // composite primary key
    }
}

Table requests.quote{
  quote_id bigint [increment, pk]
  request_id bigint [not null, ref: - requests.service_requests.request_id]
  quote_state varchar(255) [not null, note: "'QUOTED','ACCEPTED','REJECTED'"]
  client_accepted_at timestamp
  quote_amount number
  indexes {
    request_id
  }
  checks {
    `quote_state in ('QUOTED','ACCEPTED','REJECTED')`
  }
}
/* =========================================
   PHASE 2: PAYMENTS & INVOICES (DEFERRED)
   =========================================

Table payment {
  payment_id integer [increment, primary key]
  payment_state integer [not null, ref: - payment_state_def.payment_state_id]
  payment_way integer [not null, ref: - payment_way_def.payment_way_id]
  due_date timestamp [not null]
  updated_on timestamp [not null]
  indexes {
    payment_state
    payment_way
    due_date
  }
}

Table payment_state_def {
  payment_state_id integer [primary key]
  payment_state_name varchar
}

Table payment_way_def {
  payment_way_id integer [primary key]
  payment_way_name varchar
}

Table invoice {
  invoice_id integer [increment, primary key]
  payment_id integer [not null, ref: -payment.payment_id]
  print_date date
  indexes {
    payment_id
    print_date
  }
}

*/
