--liquibase formatted sql
--changeset vstavrou:003-create-user-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'user';

CREATE TABLE "entities"."user"
(
    "user_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"          varchar(255) NOT NULL UNIQUE,
    "email"             varchar(255) NOT NULL UNIQUE,
    "password"          varchar(512) NOT NULL,
    "role"              varchar(50)  NOT NULL,
    "registration_date" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chk_user_role" CHECK (role in ('ADMIN', 'VERIFIED_USER', 'NOT_VERIFIED_USER'))
);

CREATE INDEX idx_user_username ON "entities"."user" ("username");
CREATE INDEX idx_user_email ON "entities"."user" ("email");
CREATE INDEX idx_user_role ON "entities"."user" ("role");

COMMENT
ON TABLE "entities"."user" IS 'This is the table that will hold the users'' information' ;
