--liquibase formatted sql
--changeset vstavrou:003-create-user-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE WHERE table_schema = 'entities' AND table_name = 'user';

CREATE TABLE "entities"."user"
(
    "user_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"          varchar UNIQUE,
    "email"             varchar UNIQUE,
    "password"          varchar,
    "role"              varchar,
    "registration_date" timestamp DEFAULT (now()),
    CONSTRAINT "chk_user_role" CHECK (role in ('ADMIN', 'VERIFIED_USER', 'NOT_VERIFIED_USER'))
);

COMMENT
ON TABLE mytable IS 'This is the table that will hold the users'' information' ;
