--liquibase formatted sql
--changeset vstavrou:004-create-person-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'person';

CREATE TABLE "entities"."person"
(
    "person_id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name"        varchar(255),
    "middle_name"       varchar(255),
    "last_name"         varchar(255),
    "birth_date"        date,
    "sex"               varchar(255),
    "tax_id"            varchar(255) UNIQUE,
    "user_id"           bigint UNIQUE NOT NULL,
    "registration_date" timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chk_gender_values" CHECK (sex IN ('M', 'F', 'N'))
);

COMMENT
ON TABLE "entities"."person" IS 'This is the table that will hold the people''s information' ;

COMMENT
ON COLUMN "entities"."person"."sex" IS 'M/F/N';
