--liquibase formatted sql
--changeset vstavrou:004-create-person-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE WHERE table_schema = 'entities' AND table_name = 'person';

CREATE TABLE "entities"."person"
(
    "person_id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name"        varchar,
    "middle_name"       varchar,
    "last_name"         varchar,
    "birth_date"        date,
    "sex"               varchar,
    "tax_id"            varchar UNIQUE,
    "user_id"           bigint UNIQUE NOT NULL,
    "registration_date" timestamp DEFAULT (now()),
    CONSTRAINT "chk_gender_values" CHECK (sex IN ('M', 'F', 'N'))
);

COMMENT
ON TABLE mytable IS 'This is the table that will hold the people''s information' ;
