--liquibase formatted sql
--changeset vstavrou:005-create-company-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE WHERE table_schema = 'entities' AND table_name = 'company';

CREATE TABLE "entities"."company"
(
    "company_id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "company_name"      varchar,
    "contact_person_id" bigint         NOT NULL,
    "tax_id"            varchar UNIQUE NOT NULL,
    "user_id"           bigint UNIQUE  NOT NULL,
    "registration_date" timestamp DEFAULT (now())
);

COMMENT
ON TABLE mytable IS 'This is the table that will hold the companies'' information' ;
