--liquibase formatted sql
--changeset vstavrou:006-create-client-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'client';

CREATE TABLE "entities"."client"
(
    "client_id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_type"       varchar(255),
    "person_id"         bigint,
    "company_id"        bigint,
    "registration_date" timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "chk_entity_exists_client" CHECK (
        (person_id IS NOT NULL AND company_id IS NULL)
            OR
        (company_id IS NOT NULL AND person_id IS NULL)
        )
);

COMMENT
ON TABLE "entities"."client" IS 'This is the table that will hold the clients'' information. We check if the entity exists, so not orphan clients can be added.' ;
