--liquibase formatted sql
--changeset vstavrou:007-create-profession-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'profession';

CREATE TABLE "entities"."profession"
(
    "profession_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profession_name" varchar(255),
    "description"     varchar(255)
);

COMMENT
ON TABLE "entities"."profession" IS 'This is a lookup table, that holds the description and the id of the professions.' ;
