--liquibase formatted sql
--changeset vstavrou:008-create-skill-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'skill';

CREATE TABLE "entities"."skill"
(
    "skill_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "skill_name" varchar(255)
);

COMMENT
ON TABLE "entities"."skill" IS 'This is a lookup table for skill name and id.' ;
