--liquibase formatted sql
--changeset vstavrou:009-create-service-provider-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'entities' AND table_name = 'service_provider';
CREATE TABLE "entities"."service_provider"
(
    "provider_id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "person_id"             bigint,
    "company_id"            bigint,
    "profession_id"         integer NOT NULL,
    "service_base_location" geometry,
    "service_radius_meters" integer,
    CONSTRAINT "chk_entity_exists_provider" CHECK (
        (person_id IS NOT NULL AND company_id IS NULL)
            OR
        (company_id IS NOT NULL AND person_id IS NULL)
        )
);


COMMENT
ON TABLE "entities"."service_provider" IS 'This is the table that will hold the service providers'' information. We check if the entity exists, so not orphan service providers can be added.' ;