--liquibase formatted sql
--changeset vstavrou:011-create-vehicle-catalog-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'vehicles' AND table_name = 'vehicle_catalog';
CREATE TABLE "vehicles"."vehicle_catalog"
(
    "catalog_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicle_type" varchar(255),
    "brand_name"   varchar(255),
    "model_name"   varchar(255),
    "model_year"   integer
);

COMMENT
ON TABLE "vehicles"."vehicle_catalog" IS 'This is the table that will hold the vehicles as a lookup table.' ;