--liquibase formatted sql
--changeset vstavrou:012-create-user-vehicles-tbl
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'vehicles' AND table_name = 'user_vehicles';
CREATE TABLE "vehicles"."user_vehicles"
(
    "vehicle_id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_id"         bigint       NOT NULL,
    "catalog_id"        integer      NOT NULL,
    "license_plate"     varchar(255) NOT NULL,
    "color"             varchar(255) NOT NULL,
    "notes"             varchar(4000),
    "registration_date" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT
ON TABLE "vehicles"."user_vehicles" IS 'This is the table that will hold the users'' vehicles using the lookup table.' ;